---
- name: create revoked_keys and set permissions to root/600
  template:
    src: "revoked_keys.j2"
    dest: "/etc/ssh/revoked_keys"
    mode: "0600"
    owner: "{{ ssh_owner }}"
    group: "{{ ssh_group }}"
  notify: restart sshd

- name: create sshd_config and set permissions to root/600
  template:
    src: "opensshd.conf.j2"
    dest: "/etc/ssh/sshd_config"
    mode: "0600"
    owner: "{{ ssh_owner }}"
    group: "{{ ssh_group }}"
    validate: "'{{ ssh.install_dir}}/sbin/sshd -T -C user=root -C host=localhost -C addr=localhost -f %s'"
  notify: restart sshd
