---
- name: Ensure prerequisites
  package:
    state: present
    name: "{{ item }}"
  loop: "{{ prerequisites[ansible_os_family|lower] }}"

- name: Ensure build dir is present
  file:
    path: "{{ ssh.build_dir }}"
    state: directory
    recurse: true

- name: Get ssh source
  unarchive:
    src: "{{ ssh.base_url }}/openssh-{{ ssh.version }}.tar.gz"
    dest: "{{ ssh.build_dir }}"
    remote_src: true
