---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: instance
    image: ami-0204cddbf060b2420
    instance_type: t2.micro
    vpc_subnet_id: subnet-2ed37a48
    region: eu-west-1
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist:
        - slack
        - yaml
      stdout_callback: yaml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: inspec
  lint:
    name: rubocop
